# Generated by Django 3.1 on 2021-01-28 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210128_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line_1',
            new_name='address',
        ),
    ]
