# Generated by Django 3.1 on 2021-01-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210131_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
